"""Build results/numbers.json and numbers.md from result files: the single source of every reported number.

    python scripts/build_numbers.py"""
import json
import sys
import os
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from utils import RESULTS_DIR, RUNS_DIR, PROJECT_ROOT  # noqa: E402

LEAKY_TAGS = {'': 'baseline (aug bug)', 'aug': 'augmentation fixed', 'reg': 'aug + regularised'}
LABELS = {
    'base_vidsplit': 'EfficientNet-B4, no augmentation', 'aug_vidsplit': 'EfficientNet-B4, augmentation (incumbent)',
    'reg_vidsplit': 'EfficientNet-B4, augmentation + regularised', 'b0_vidsplit': 'EfficientNet-B0',
    'r50_vidsplit': 'ResNet-50', 'xcep_vidsplit': 'Xception', 'cnxt_vidsplit': 'ConvNeXt-Tiny',
    'mm_r50_vidsplit': 'ResNet-50, multi-method', 'mm_xcep_vidsplit': 'Xception, multi-method',
    'mm_b0_vidsplit': 'EfficientNet-B0, multi-method', 'mm_cnxt_vidsplit': 'ConvNeXt-Tiny, multi-method',
    'mm_b4_vidsplit': 'EfficientNet-B4, multi-method',
    'mm_b4reg_vidsplit': 'EfficientNet-B4, multi-method, regularised',
}


def ms(vals):
    v = np.array(vals, dtype=float)
    return {'mean': float(v.mean()), 'std': float(v.std(ddof=1)) if len(v) > 1 else 0.0, 'n': int(len(v))}


def load(p):
    try:
        return json.load(open(p))
    except (OSError, json.JSONDecodeError):
        return None


def run_dirs(tag):
    root = RUNS_DIR / tag if tag else RUNS_DIR
    return sorted(d for d in root.glob('seed*') if (d / 'metrics.json').exists())


def video_entry(tag):
    dirs = run_dirs(tag)
    if not dirs:
        return None
    runs = []
    for d in dirs:
        m = load(d / 'metrics.json')
        if 'eer' not in m:                                    # legacy runs keep EER in threshold_analysis.json
            m['eer'] = (load(d / 'threshold_analysis.json') or {}).get('eer_test')
        runs.append((m, load(d / 'history.json'), load(d / 'train_config.json')))
    e = {'label': LABELS.get(tag, LEAKY_TAGS.get(tag, tag)),
         'split': 'v1 (leaking, SUPERSEDED)' if tag in LEAKY_TAGS else 'v2 identity-disjoint',
         'seeds': [m['seed'] for m, _, _ in runs], 'test_crops': runs[0][0].get('test_crops'),
         'arch': (runs[0][2] or {}).get('arch', 'efficientnet_b4'),
         'frames_dir': (runs[0][2] or {}).get('frames_dir', 'frames'),
         'frame_level': {k: ms([m[k] for m, _, _ in runs]) for k in ('accuracy', 'f1', 'auc_roc', 'eer')
                         if all(m.get(k) is not None for m, _, _ in runs)}}
    if all('video_level' in m for m, _, _ in runs):
        e['video_level'] = {'n_videos': runs[0][0]['video_level']['n_videos'],
                            **{k: ms([m['video_level'][k] for m, _, _ in runs]) for k in ('accuracy', 'f1', 'auc_roc', 'eer')}}
    hs = [h for _, h, _ in runs if h and h.get('train_acc')]
    if hs:
        e['overfitting_gap_pp'] = ms([(h['train_acc'][-1] - h['val_acc'][-1]) * 100 for h in hs])
        picks = [int(np.argmax(h['val_acc'])) for h in hs]
        e['val_accuracy_at_best_epoch'] = ms([h['val_acc'][i] for h, i in zip(hs, picks)])
        e['best_val_acc_epochs'] = [i + 1 for i in picks]
        e['lowest_val_loss_epochs'] = [int(np.argmin(h['val_loss'])) + 1 for h in hs]
    return e


def fmt(x, pct=False, places=4):
    if x is None:
        return 'n/a'
    if x.get('n', 2) < 2:                                    # one seed: no spread to report, do not imply zero
        return f'{x["mean"] * 100:.2f}% (n=1)' if pct else f'{x["mean"]:.{places}f} (n=1)'
    return (f'{x["mean"] * 100:.2f} ± {x["std"] * 100:.2f}%' if pct else f'{x["mean"]:.{places}f} ± {x["std"]:.{places}f}')


def main():
    out = {'generated_at': datetime.now(timezone.utc).isoformat(timespec='seconds'),
           'note': 'Generated by scripts/build_numbers.py from result files. Do not edit by hand.'}

    split = load(PROJECT_ROOT / 'data_splits' / 'split_v2_identity_grouped.json')
    if split:
        out['split_v2'] = {k: split[k] for k in ('name', 'sha256', 'n_frames', 'n_videos')}

    tags = ['', 'aug', 'reg'] + sorted(d.name for d in RUNS_DIR.iterdir() if d.is_dir() and d.name.endswith('_vidsplit'))
    out['video'] = {}
    for tag in tags:
        e = video_entry(tag)
        if e:
            out['video'][tag or 'baseline_legacy'] = e

    out['cross_method'] = {}
    for f in sorted((RESULTS_DIR / 'cross_method').glob('*/cross_method.json')):
        d = load(f)
        out['cross_method'][d['tag']] = {'seeds': d['seeds'], 'note': d['note'], 'mean_std': d['mean_std']}

    out['cross_validation'] = {}
    for f in sorted((RESULTS_DIR / 'cv').glob('*/cv_summary.json')):
        cv = load(f)
        # Record which architecture the CV describes (read from its first fold's config), so an interval measured for one
        # architecture is never attached to a different shipped model by the app or the report.
        first = sorted(RUNS_DIR.glob(f'{cv["name"].split("_mm")[0]}_f0/seed*/train_config.json'))
        cfg = load(first[0]) if first else None
        cv['arch'] = (cfg or {}).get('arch')
        cv['frames_dir'] = (cfg or {}).get('frames_dir')
        out['cross_validation'][f.parent.name] = cv
    out['audio'] = {'wav2vec2_svm_full': load(RESULTS_DIR / 'audio_branch' / 'metrics.json'),
                    'encoder_comparison_subsample': load(RESULTS_DIR / 'audio_encoder_comparison' / 'comparison.json'),
                    'channel_diagnostic': load(RESULTS_DIR / 'audio_channel_diagnostic' / 'diagnostic.json'),
                    'wav2vec2_svm_extra': load(RESULTS_DIR / 'audio_branch' / 'extra_metrics.json'),
                    'baseline_comparison': load(RESULTS_DIR / 'audio_baseline' / 'metrics.json')}
    out['cross_dataset_celebdf_v2_OLD_MODEL'] = load(RESULTS_DIR / 'cross_dataset' / 'celebdf_v2' / 'metrics.json')
    # One run per candidate model (best-validation seed), zero-shot on the official 518-video test list.
    out['cross_dataset_celebdf_v2'] = {}
    for f in sorted((RESULTS_DIR / 'cross_dataset').glob('celebdf_v2__*/metrics.json')):
        d = load(f)
        seed = Path(d['model_path']).stem.replace('seed', '')
        out['cross_dataset_celebdf_v2'][f.parent.name.replace('celebdf_v2__', '')] = {
            'arch': d.get('arch'), 'seed': int(seed) if seed.isdigit() else None, 'n_videos': d['n_videos_evaluated'],
            'n_real': d['n_real'], 'n_fake': d['n_fake'], 'accuracy': d['accuracy'], 'auc_roc': d['auc_roc'],
            'eer': d['eer'], 'fake_detection': d['recall'], 'real_specificity': d['confusion_matrix'][0][0] / d['n_real']}
    out['fallback_4condition_OLD_MODEL'] = (load(RESULTS_DIR / 'fallback_eval' / 'fallback_4condition_results.json') or {}).get('conditions')
    out['hybrid_4condition_OLD_MODEL'] = (load(RESULTS_DIR / 'hybrid_eval' / 'fallback_4condition_results.json') or {}).get('conditions')
    # Re-runs on the SHIPPED model are written to *_shipped folders and appear here WITHOUT the OLD suffix, so the
    # app's Evaluation tab switches from "pending" to the new figures by itself. Nothing is copied by hand.
    for key, folder in (('fallback_4condition', 'fallback_eval_shipped'), ('hybrid_4condition', 'hybrid_eval_shipped')):
        d = load(RESULTS_DIR / folder / 'fallback_4condition_results.json') or {}
        out[key] = d.get('conditions')
        # The four accuracies alone can look good while the project's actual contribution fails: keep the
        # modality-implication metrics beside them (docs/EXPERIMENTS.md H2, docs/LESSONS.md L28).
        out[key + '_implication'] = d.get('core_research_question_metrics')
    out['threshold_tuning_shipped'] = load(RESULTS_DIR / 'fallback_eval_shipped' / 'threshold_tuning.json')
    # HELD-OUT four-condition set (eval_heldout/, built from test-split identities only) is the authoritative one; the older
    # fallback set is in-distribution for the video branch (docs/EXPERIMENTS.md F3 caveat, F5, docs/LESSONS.md L29).
    ho = load(RESULTS_DIR / 'heldout_eval_shipped' / 'fallback_4condition_results.json') or {}
    out['heldout_4condition'] = ho.get('conditions')
    out['heldout_4condition_implication'] = ho.get('core_research_question_metrics')
    out['heldout_threshold_tuning'] = load(RESULTS_DIR / 'heldout_eval_shipped' / 'threshold_tuning.json')
    out['heldout_advantage_bootstrap'] = load(RESULTS_DIR / 'heldout_eval_shipped' / 'advantage_bootstrap.json')
    out['fallback_advantage_bootstrap'] = load(RESULTS_DIR / 'fallback_eval_shipped' / 'advantage_bootstrap.json')
    # How many of the older set's videos the shipped model's split had in TRAINING: derived from the two manifests, never typed.
    split_a = (load(PROJECT_ROOT / 'data_splits' / 'split_v2_identity_grouped.json') or {}).get('assignment')
    fb = load(PROJECT_ROOT / 'eval_fallback' / 'manifest.json')
    if split_a and fb:
        roles = {}
        for c in fb['clips']:
            k = ('real/' if c['video_label'] == 'real' else 'fake/') + os.path.basename(c['video_source'])[:-4]
            r = split_a.get(k, 'unknown')
            roles[r] = roles.get(r, 0) + 1
        out['fallback_set_video_membership'] = {'n_clips': len(fb['clips']), **roles}
    out['shipped_model'] = load(PROJECT_ROOT / 'models' / 'shipped_model.json')
    json.dump(out, open(RESULTS_DIR / 'numbers.json', 'w'), indent=2)

    L = ['# Results (generated by scripts/build_numbers.py; do not edit)\n',
         f'Generated {out["generated_at"]}. Split v2: {out.get("split_v2", {}).get("sha256", "n/a")[:12]}.\n',
         '## Video branch, frame level (per crop; secondary) and clip level (n = test videos)\n',
         '| Run | Split | Frame acc | Frame AUC | Frame EER | Clip acc | Clip AUC | Overfit gap | Val acc |',
         '|---|---|---|---|---|---|---|---|---|']
    for tag, e in out['video'].items():
        v = e.get('video_level')
        L.append(f'| {e["label"]} | {e["split"]} | {fmt(e["frame_level"]["accuracy"], True)} | {fmt(e["frame_level"]["auc_roc"])} | '
                 f'{fmt(e["frame_level"].get("eer"), True)} | {fmt(v["accuracy"], True) if v else "n/a"} | '
                 f'{fmt(v["auc_roc"]) if v else "n/a"} | '
                 f'{fmt(e.get("overfitting_gap_pp"), places=2) + " pp" if e.get("overfitting_gap_pp") else "n/a"} | '
                 f'{fmt(e.get("val_accuracy_at_best_epoch"), True) if e.get("val_accuracy_at_best_epoch") else "n/a"} |')
    if out['cross_method']:
        L += ['\n## Per-method detection (clip level; test-split identities; 22 real + 22 fake videos per method)\n',
              'Single-method models: FaceSwap and NeuralTextures are zero-shot (never seen). Multi-method models: all three methods were seen in training, identities were not.\n',
              '| Model | Deepfakes AUC | FaceSwap AUC | NeuralTextures AUC | FaceSwap detected | NeuralTextures detected |',
              '|---|---|---|---|---|---|']
        for tag, d in out['cross_method'].items():
            m = d['mean_std']
            L.append(f'| {LABELS.get(tag, tag)} | {fmt(m["Deepfakes"]["auc_roc"], places=3)} | {fmt(m["FaceSwap"]["auc_roc"], places=3)} | '
                     f'{fmt(m["NeuralTextures"]["auc_roc"], places=3)} | {fmt(m["FaceSwap"]["fake_detection_rate"], True)} | '
                     f'{fmt(m["NeuralTextures"]["fake_detection_rate"], True)} |')
    a = out['audio']['baseline_comparison']
    if a:
        u = a['unseen_corpus_genuine_speech']
        L += ['\n## Audio front end (ASVspoof 2019 LA, full) and unseen-corpus false alarms\n',
              '| Front end | Eval EER | Eval acc | False alarms on genuine unseen speech |', '|---|---|---|---|',
              f'| MFCC + SVM | {a["mfcc_svm"]["eval_eer"] * 100:.2f}% | {a["mfcc_svm"]["eval_accuracy"]:.4f} | {u["mfcc_svm"]["fa_at_p0.5"] * 100:.0f}% of {u["n_clips"]} clips |',
              f'| wav2vec2 + SVM | {a["wav2vec2_svm"]["eval_eer"] * 100:.2f}% | {a["wav2vec2_svm"]["eval_accuracy"]:.4f} | '
              f'{u.get("wav2vec2_svm", {}).get("fa_at_p0.5", float("nan")) * 100:.0f}% of {u["n_clips"]} clips |']
    x = out['audio'].get('wav2vec2_svm_extra')
    if x:
        b1 = x['at_svm_decision_boundary (clf.predict, as in metrics.json)']
        b2 = x['at_probability_0.5 (as the app and fusion use it)']
        L += [f'\n## Audio branch, full metric set (ASVspoof 2019 LA eval: {x["n_bonafide"]} bona fide + {x["n_spoof"]} spoof; spoof = positive)\n',
              f'AUC-ROC {x["auc_roc"]:.4f}, EER {x["eer"] * 100:.2f}%. Always answering "spoof" would score {x["majority_class_baseline_accuracy"] * 100:.1f}% '
              'accuracy, so plain accuracy flatters this classifier on an imbalanced set; balanced accuracy and per-class F1 are given.\n',
              '| Metric | At the SVM decision boundary (as in metrics.json) | At P(fake) >= 0.5 (as the app and fusion use it) |', '|---|---|---|']
        for key, lab in (('accuracy', 'Accuracy'), ('balanced_accuracy', 'Balanced accuracy'), ('f1_spoof', 'F1 (spoof)'),
                         ('f1_bonafide', 'F1 (bona fide)'), ('f1_macro', 'Macro F1'), ('specificity_bonafide_recall', 'Bona fide recall'),
                         ('recall_spoof', 'Spoof recall')):
            L.append(f'| {lab} | {b1[key]:.4f} | {b2[key]:.4f} |')
    if out['cross_dataset_celebdf_v2']:
        L += ['\n## Cross-dataset: Celeb-DF-v2, zero-shot (official test list, 178 real + 340 fake videos; one seed per model)\n',
              'Seed = best validation accuracy of that tag. Uses the training-style JPEG round trip at inference (decision D4).\n',
              '| Model | Seed | Accuracy at 0.5 | AUC-ROC | EER | Fake detection | Real specificity |', '|---|---|---|---|---|---|---|']
        for tag, c in out['cross_dataset_celebdf_v2'].items():
            L.append(f'| {LABELS.get(tag, tag)} | {c["seed"]} | {c["accuracy"] * 100:.1f}% | {c["auc_roc"]:.3f} | {c["eer"] * 100:.1f}% | '
                     f'{c["fake_detection"] * 100:.1f}% | {c["real_specificity"] * 100:.1f}% |')
    for name, cv in out.get('cross_validation', {}).items():
        po, c = cv['pooled_out_of_fold'], cv['ci95_cluster_bootstrap']
        L += [f'\n## Cross-validation (out-of-fold, {po["n_videos"]} videos, {len(cv["folds"])} folds): {name}\n',
              '| Metric | Pooled | 95% CI (identity-cluster bootstrap) |', '|---|---|---|']
        for key, lab, pct in (('auc', 'AUC-ROC', False), ('accuracy', 'Accuracy at 0.5', True), ('real_specificity', 'Real specificity', True),
                              ('fake_detection', 'Fake detection', True), ('detect_FaceSwap', 'FaceSwap detected', True),
                              ('detect_NeuralTextures', 'NeuralTextures detected', True), ('ece10', 'ECE (10 bins)', False)):
            if key in po:
                f = (lambda v: f'{v * 100:.1f}%') if pct else (lambda v: f'{v:.3f}')
                L.append(f'| {lab} | {f(po[key])} | {f(c[key][0])} to {f(c[key][1])} |')
    L.append('\nSections marked OLD_MODEL in numbers.json were produced with the superseded video model and must be re-run '
             'before being quoted.')
    (RESULTS_DIR / 'numbers.md').write_text('\n'.join(L) + '\n')
    print('\n'.join(L))


if __name__ == '__main__':
    main()
